language: ruby
sudo: false

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1

gemfile:
  - Gemfile.rails42
  - Gemfile.rails50

matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: Gemfile.rails50

services:
  - mysql

before_script:
  - mysql -e 'create database ar_transaction_changes_test'
